### ISSUE TITLE
Install on OS X asks for non-existing "nfftw3util.h"

### ISSUE THREAD

**Issue by ltalirz** [ghisvail/pyNFFT#56]
I have successfully built nfftw3 from source (with --enable-openmp) using gcc 5.4 from macports.

I then tried to install pynfft, first using pip 
```bash
export CC=gcc # avoids clang problem #53
pip install pynfft
```
and, later, from the source on github.

The build, however, fails with the error message

`/Users/leoteo/Scratch/tst/pyNFFT-master/pynfft/util.c:439:23: fatal error: nfft3util.h: No such file or directory compilation terminated.`

Looking into util.c, I find 
```c
...
#include "nfft3.h"
#include "fftw3.h"
#include "nfft3util.h"
...
```
I.e. the first two includes work fine, only nfft3util.h fails.

nfft3util.h is not provided by nfft 3.3.2 (at least not using default configure options).
I have been searching the codebase of nffftw3 (https://github.com/NFFT/nfft) but I can't seem to find any mention of a header nfft3util.h. 

What am I missing?

**Comment by ghisvail** [comment]
I believe `nfft3util.h` is no longer installed by the latest version of `NFFT`.

**Comment by ltalirz** [comment]
Thanks for the immediate answer!

Was some functionality in nfft3 scrapped or did it just move to another place?

When I uncomment the #include "nfft3util.h" in util.c, the build goes through but I guess this means some parts of the python module will be unusable?
The test in pynfft.tests.test_nfft fails with

```
E
======================================================================
ERROR: pynfft.tests.test_nfft (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: pynfft.tests.test_nfft
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "pynfft/tests/test_nfft.py", line 23, in <module>
    from pynfft.util import vrand_unit_complex, vrand_shifted_unit_double
ImportError: dlopen(pynfft/util.so, 2): Symbol not found: _nfft_voronoi_weights_S2
  Referenced from: pynfft/util.so
  Expected in: flat namespace
 in pynfft/util.so
```

How should I proceed?

**Comment by ltalirz** [comment]
A relevant commit is this one

commit NFFT/nfft@9f91543bbc7271d1a8cc9c21cfc87287f921bdfe
Author: Jens Keiner <jens@nfft.org>
Date:   Wed Jul 25 20:17:55 2012 +0000

    Removed remaining definitions from util/util.c and include/nfft3util.h. The implementation has mostly been moved into kernel/util/ and the include/infft.h.


It seems that things have moved into infft.h but unfortunately infft.h is not meant to be installed together with nfft3 (at least not by default).
I tried pointing the python build towards the include directory of the nfft-3.3.2 source (replacing "nfft3util.h" by "infft.h") and it went through but the unit test still fails.

**Comment by ghisvail** [comment]
Most of the relevant utilities are now in `nfft3.h` anyway

**Comment by ghisvail** [comment]
Indeed I have not kept the package up-to-date with the recent developments of NFFT. I should probably merge the current patches applied on Debian and do a new release.

**Comment by ltalirz** [comment]
If you can find the time, I am sure that would be greatly appreciated - and not only be me :)

**Comment by ghisvail** [comment]
Time is a bit sparse these days so I cannot promise a definitive ETA. Meanwhile, feel free to submit a PR if you have something working.

**Comment by MaxSchambach** [comment]
This issue is resolved by #58. It would be very nice if you find the time to update the PyPI package accordingly. Building from source works without trouble now.
